# Site settings
title: Your Blog Title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yourdomain.com" # Change this to your actual domain

twitter_username: your_twitter
github_username: your_github

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# GitHub Pages settings
remote_theme: jekyll/minima

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Collections for organizing content
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

# Default layouts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Your Name"
  - scope:
      path: ""
    values:
      layout: "default"

# Social media and customization
social:
  name: Your Name
  links:
    - https://twitter.com/your_twitter
    - https://github.com/your_github

# SEO settings
google_analytics: # Add your Google Analytics ID here if you want tracking 