# Site settings
title: WADBRANT
email: williamwadbr@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Endless curiosity, love to enable others, & doing what matters. Product Management, Gaming Industry, & AI.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wadbrant.com" # Change this to your actual domain

twitter_username: WilliamWadbrant
github_username: WasingOfWill
linkedin_username: Wadbrant

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# GitHub Pages settings
remote_theme: jekyll/minima

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Collections for organizing content
collections:
  posts:
    output: true
    permalink: /:day/:month/:year/:title/

# Default layouts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Your Name"
  - scope:
      path: ""
    values:
      layout: "default"

# Social media and customization
social:
  name: Will Wadbrant
  links:
    - https://twitter.com/WilliamWadbrant
    - https://github.com/WasingOfWill
    - https://www.linkedin.com/in/wadbrant/

# SEO settings
google_analytics: G-HVDB517FPM